config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'profiles#index'
  get '/home', to: 'profiles#home', as: :home

  get '/profiles/search', to: 'profiles#search', as: :search_developer
  post '/profiles/search', to: 'profiles#search_filter', as: :search_developer_post
  
  get '/:username', to: 'profiles#show', as: :profile
  get '/users/edit_links', to: 'profiles#edit_links', as: :edit_links
  post '/users/update_links', to: 'profiles#update_links'

  get '/integrations/codeforces/new', to: 'codeforces_profile#new', as: :cfp_profile_new
  post '/integrations/codeforces/create', to: 'codeforces_profile#create'
  get '/integrations/codeforces/recent_submissions/:handle', to: 'codeforces_profile#recent_submissions', as: :cfp_submissions
  get '/integrations/codeforces/show/:username', to: 'codeforces_profile#show_cfp_profile', as: :cfp_show_profile
  get '/integrations/codeforces/update', to: 'codeforces_profile#update', as: :cfp_update_profile
  get '/integrations/codeforces/delete', to: 'codeforces_profile#delete', as: :cfp_delete_profile

  get '/integrations/edit', to: 'profiles#edit_integrations', as: :edit_integrations

  get '/integrations/github/create', to: 'github_profile#create', as: :github_profile_create
  get '/integrations/github/show/:username', to: 'github_profile#show', as: :github_show_profile
  get '/integrations/github/update', to: 'github_profile#update', as: :github_update_profile
  get '/integrations/github/delete', to: 'github_profile#delete', as: :github_delete_profile 

  get '/integrations/topcoder/new', to: 'topcoder_profile#new', as: :topcoder_profile_new
  post '/integrations/topcoder/create', to: 'topcoder_profile#create', as: :topcoder_profile_create
  get '/integrations/topcoder/show/:username', to: 'topcoder_profile#show_tcp_profile', as: :tcp_show_profile
  get '/integrations/topcoder/update', to: 'topcoder_profile#update', as: :topcoder_update_profile
  get '/integrations/topcoder_profile/delete', to: 'topcoder_profile#delete', as: :topcoder_delete_profile

  get '/integrations/linkedin/create', to: 'linkedin_profile#create', as: :linkedin_profile_create
  get '/integrations/linkedin/show/:username', to: 'linkedin_profile#show_profile', as: :linkedin_show_profile
  post '/integrations/linkedin/refine', to: 'linkedin_profile#refine', as: :linkedin_refine
  get '/integrations/linkedin/update', to: 'linkedin_profile#update', as: :linkedin_update_profile
  get '/integrations/linkedin/delete', to: 'linkedin_profile#delete', as: :linkedin_delete_profile 

  get '/mails/new/:username', to: 'mails#new', as: :new_mails
  post '/mails/send/:username', to: 'mails#send_mail', as: :send_mails
  get '/mails/delete/:id', to: 'mails#delete' , as: :delete_mails

end

app/models/topcoder_profile.rb
class TopcoderProfile < ActiveRecord::Base
	belongs_to :user

	def self.get(url)
		begin
			resp = RestClient.get(url)
			resp = JSON.parse(resp)
			if resp.class.to_s == "Array"
				resp = {"result" => resp}
			end
			resp.merge!("status" => "OK")
			return resp
		rescue
			return {"status" => "bad_request"}
		end
	end

	def self.connect(handle)
		key = ENV['TC_KEY']
		url = "http://api.topcoder.com/rest/statistics/#{handle}?user_key=#{key}"
		resp = self.get(url)
		return resp
	end

	def self.get_achievements(handle)
		key = ENV['TC_KEY']
		url = "http://api.topcoder.com/rest/statistics/#{handle}/achievements?user_key=#{key}"
		resp = self.get(url)
		return resp
	end

	def self.refine_basic_info(response_info)
		response_info.delete("handle")
		response_info.delete("status")
		response_info.delete("country")
		response_info["ratingsSummary"].each do |rating|
			rating.delete("colorStyle")
		end
		response_info
	end

	def self.refine_achievements(response_achivs)
		achievements = response_achivs["result"]
		achievements.each do |a|
			a["badgeLink"].delete("url")
		end
		achievements
	end

end

app/controllers/topcoder_profile_controller.rb
class TopcoderProfileController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :create]

	def new
	end

	def create
		handle = params[:handle]

		begin
			response_info = TopcoderProfile.connect(handle)
			status_info = response_info["status"]

			if status_info=="OK"
				response_info = TopcoderProfile.refine_basic_info(response_info)

				@tpf = TopcoderProfile.create(user_id: current_user.id, handle: handle, data: response_info)

				response_achivs = TopcoderProfile.get_achievements(handle)
				status_achivs = response_achivs["status"]

				if status_achivs=="OK"
					data = @tpf.data
					achievements = TopcoderProfile.refine_achievements(response_achivs)
					data.merge!("achievements" => achievements)

					@tpf.data = data
					@tpf.data_will_change!
					@tpf.save!
				end

				#Update Last updated at attribute
				current_user.profile_updated_at = Time.now
				current_user.save!
				current_user.reload

				flash[:notice] = "You have successfully integrated Topcoder in your profile."
				redirect_to profile_path(username: current_user.username)
			else
				flash[:alert] = "It seems your credentials are not authentic or something went wrong."
				redirect_to :back
			end
		rescue Exception => e
			tcp = current_user.topcoder_profile
			unless tcp.nil?
				tcp.destroy
			end
			flash[:alert] = "It seems your credentials are not authentic or something went wrong."
			redirect_to :back
		end
	end

	def update
		@tpf = current_user.topcoder_profile

		if @tpf.nil?
			flash[:alert] = "You don't have Topcoder account integrated with your profile."
			redirect_to :back
		else
			if @tpf.updated_at < Time.now - 12.hours
				begin
					handle = @tpf.handle
					response_info = TopcoderProfile.connect(handle)
					status_info = response_info["status"]

					if status_info=="OK"
						response_info = TopcoderProfile.refine_basic_info(response_info)

						@tpf.update_attributes(data: response_info)

						response_achivs = TopcoderProfile.get_achievements(handle)
						status_achivs = response_achivs["status"]

						if status_achivs=="OK"
							data = @tpf.data
							achievements = TopcoderProfile.refine_achievements(response_achivs)
							data.merge!("achievements" => achievements)

							@tpf.data = data
							@tpf.data_will_change!
							@tpf.save!

							#Update Last updated at attribute
							current_user.profile_updated_at = Time.now
							current_user.save!
							current_user.reload

							flash[:notice] = "You have successfully integrated Topcoder in your profile."
							redirect_to profile_path(username: current_user.username)
						else
							flash[:alert] = "Sorry, something went wrong. Try again later."
							redirect_to :back
						end
					else
						flash[:alert] = "It seems your credentials are not authentic or something went wrong."
						redirect_to :back
					end
				rescue Exception => e
					@tpf.data = old_data
					@tpf.data_will_change!
					@tpf.save!
					current_user.reload
					flash[:alert] = "It seems your credentials are not authentic or something went wrong."
					redirect_to :back
				end
			else
				flash[:alert] = "Don't update frequently. Wait for atleast 12 hours."
				redirect_to :back
			end
		end
	end

	def show_tcp_profile
		@user = User.where(username: params[:username]).first
		if @user.nil?
			render file: 'public/404', status: 404, formats: [:html]
		else
			@tcp = @user.topcoder_profile


			respond_to do |format|
				format.js
				format.html
			end
		end
	end

	def delete
		unless current_user.topcoder_profile.nil?
			TopcoderProfile.where(:user => current_user).first.destroy
	 		current_user.save!
	 		current_user.reload
	 	end
		respond_to do |format|
			format.js
		end	
	end

end

app/views/topcoder_profile/_add_topcoder.html.erb
<% if @user == current_user %>
	<div class="row" style="margin-top: 20px; margin-left: 25%; margin-bottom: 20px;">
		<strong>You have not integrated Topcoder Profile. You can Integrate it from below link.</strong>
	</div>
	<div class="row">
		<div class="col-lg-6 col-lg-offset-2">
			<%= image_tag("topcoder_small.png", class: "sitelogo", style: "width: 50px; height: 50px;") %>
				&nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Topcoder</strong>
		</div>
		<div class="col-lg-4">
			<a href="<%= topcoder_profile_new_path %>" class="btn btn-info btn-perspective"><i class="fa fa-plus-circle"></i>&nbsp;Add</a>&nbsp;
		</div>
	</div>
<% else %>
	<div class="row" style="margin-top: 20px; margin-left: 25%; margin-bottom: 20px;"> 
	<strong><h3><%= @user.username %> has not integrated Topcoder profile.</h3> </strong>
	</div>
<% end -%>

app/views/topcoder_profile/_edit.html.erb
<div class="col-lg-6 col-lg-offset-2">
		<%= image_tag("topcoder_small.png", class: "sitelogo", style: "width: 50px; height: 50px;") %> &nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Topcoder</strong>
	</div>
	<div class="col-lg-4">
		<% if current_user.topcoder_profile.nil? %>
		<a href="<%= topcoder_profile_new_path %>" class="btn btn-info btn-perspective"><i class="fa fa-plus-circle"></i>&nbsp;Add</a>&nbsp;
		<% else %>
		<a href="<%= topcoder_update_profile_path %>" class="btn btn-success btn-perspective"><i class="fa fa-pencil-square-o"></i>Update</a>
		<a href="javascript:void(0)" class="btn btn-danger btn-perspective" id="delete_topcoder"><i class="fa fa-minus-circle"></i>&nbsp;Remove</a>&nbsp;
		<% end -%>
</div>

<script type='text/javascript'>
		$(document).ready(function() {
		  	$('#delete_topcoder').on("click",function(){
				ajaxLoad("<%= topcoder_delete_profile_path %>");
		  	});
		});
</script>

app/views/topcoder_profile/_show.html.erb
<% if not @tcp.nil? %>
	<div class="row">
		<div class="col-lg-12">
			<%= image_tag("topcoder_small.png", class: "sitelogo", style: "width: 50px; height: 50px;") %> &nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Topcoder</strong>
		</div>
	</div>
	<div class="logoline row">
		<div class="col-lg-6">
			<div class="row">
				<div class="col-lg-12">
					<div class="text-center panel-no-border panel-success panel-block-color panel-square" style="margin-bottom: 20px;">
						<div class="panel-heading">
							<h4 class="panel-title"> @<%= @tcp.handle %> </h4>
						</div>
						<div class="panel-body bg-success">
							<p>  (Topcoder since <%= @tcp.data["memberSince"] %>)  </p>
						</div>
					</div>
				</div>
			</div>
			<!--  -->
			<div class="row">
				<div class="col-lg-6">
					<div class="panel panel-info panel-square panel-no-border text-center">
					  <div class="panel-heading">
						<h3 class="panel-title">Total Earnings</h3>
					  </div>
					  <div class="panel-body">
						<h2 class="bolded tiles-number text-info"><i class="fa fa-usd"></i><%= @tcp.data["overallEarning"] %></h2>
					  </div><!-- /.panel-body -->
					</div>
				</div>
				<div class="col-lg-6">
					<div class="panel panel-warning panel-square panel-no-border text-center" style="margin-bottom:10px;">
					  <div class="panel-heading">
						<h3 class="panel-title">Years of Experience</h3>
					  </div>
					  <div class="panel-body">
						<h2 class="bolded tiles-number text-warning"><%= distance_of_time_in_words_to_now(date_format(@tcp.data["memberSince"])) %></h2>
					  </div><!-- /.panel-body -->
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-6">
			<div class="the-box no-border full">
				<div class="the-box bg-dark no-border no-margin">
					<p class="text-center"><i class="fa  fa-quote-left icon-md"></i></p>
					<h4 class="bolded less-distance text-danger text-center">
						<% if not @tcp.data["quote"].blank? %>
							<%= @tcp.data["quote"] %>
						<% else %>
							It's up to you how far you go. If you don't try, you'll never know!
						<% end -%>
					</h4>
				</div><!-- /.the-box no-border no-margin -->
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-6 col-md-12 col-sm-12">
			<!-- BEGIN NEWS TICKER WIDGET -->
			<div class="the-box no-border full">
				<% if not @tcp.data["achievements"].nil? %>
					<h4 class="text-center bg-primary" style="padding-top:10px;padding-bottom:10px;margin-bottom:0px;margin-top:-1px;">Achievements (<%= @tcp.data["achievements"].count %>)</h4>
				<% else %> 
					<!-- <h4 class="text-center bg-primary" style="padding-top:10px;padding-bottom:10px;margin-bottom:0px;margin-top:-1px;">Achievements (0)</h4> -->
				<% end %> 
					<button class="btn btn-block btn-primary btn-square" id="w-newsticker-next"><i class="fa fa-chevron-up"></i></button>
					<ul class="widget-newsticker media-list" >
						<% if not @tcp.data["achievements"].nil? %>
								<% @tcp.data["achievements"].each do |i| %>
								<li class="media"  style="height: 90px;">
									<a class="pull-left" href="javascript:void(0)">
										<div class="crop" style="width: 48px; height: 42px; overflow: hidden;" data-toggle="tooltip" title="Hello">
										<% if not i["badgeLink"].blank? %>
 											<img src="http://www.topcoder.com/images/badge.grid.small.png"  style="width: 255px; height: 918px; margin: <%= i["badgeLink"]["topOffset"]*3 %>px -0px -0px <%= i["badgeLink"]["leftOffset"]*3 %>px;"/>
 										<% else %>
 											<img src="http://www.topcoder.com/images/badge.grid.small.png"  style="width: 255px; height: 918px; margin: -714px -0px -0px 0px;"/>
 										<% end -%>
										</div>
									</a>
									<div class="media-body">
									  <h4 class="media-heading"><a href="widget-default.html#fakelink"><%= i["description"] %></a></h4>
									  <p class="text-muted"><small>achieved on <%= date_format(i["date"]).to_date %></small></p>
									</div>
								</li>
								<% end -%>
						<% else %>
							<li class="media" style="height: 90px">
									<a class="pull-left" href="javascript:void(0)">
										<div class="crop" style="width: 90px; height: 70px; overflow: hidden;" data-toggle="tooltip" title="Hello", id="tooltip1">
											<!-- <img src="http://www.topcoder.com/images/badge.grid.small.png"  style="width: 425px; height: 1530px; margin: -1190px -0px -0px -255px;"/> -->
										</div>
									</a>
									<div class="media-body">
										<% if @user == current_user %>
											You have no achievements to show
										<% else %>
											<%= @user.full_name %> doesn't have any achievement to show
										<% end -%>
									</div>
								</li>
						<% end -%>
					</ul>
					<button class="btn btn-block btn-primary btn-square" id="w-newsticker-prev"><i class="fa fa-chevron-down"></i></button>

			</div><!-- /.the-box no-border -->
			<!-- END NEWS TICKER WIDGET -->
		</div>
		<div class="col-lg-6">
			<% @tcp.data["ratingsSummary"].each_with_index do |item, i| %>
			<div class="col-lg-6">
				<div class="the-box no-border full text-center">
					<div class="the-box no-border bg-<%=color(i)%> no-margin">
						<h4 class="less-distance">Rating</h4>
						<i class="fa fa-<%= icon(item["name"]) %> icon-xl-size"></i>
						<h1 class="bolded less-distance"><%= item["rating"] %></h1>
					</div><!-- /.the-box no-border bg-primary no-margin -->
					<div class="the-box no-border no-margin">
						<h4 class="bolded less-distance"><%= item["name"] %></h4>
					</div><!-- /.the-box no-border no-margin -->
				</div>
			</div>
			<% end -%>
		</div>
	</div>

<script type="text/javascript">
	if ($('.widget-newsticker').length > 0){
		$('.widget-newsticker').newsTicker({
			row_height: 90,
			<% if not @tcp.data["achievements"].nil? %>
				<% if @tcp.data["achievements"].count > 3 %>
					max_rows: 3,
				<% elsif @tcp.data["achievements"].count > 1 %>
					max_rows: 1,
				<% end -%>
			<% else %>
				max_rows: 0.5,
			<% end -%>
			speed: 600,
			direction: 'up',
			duration: 4000,
			autostart: 1,
			pauseOnHover: 1,
			prevButton: $('#w-newsticker-next'),
			nextButton: $('#w-newsticker-prev')
		});
	}

	$("[data-toggle=tooltip]").tooltip();
</script>
<% else %>
	<%= render partial: 'add_topcoder' %>
<% end -%>

app/views/topcoder_profile/delete.js.erb
$('#topcoder_edit').html("<%= escape_javascript render(:partial => 'edit') %>");

app/views/topcoder_profile/new.html.erb
<script type="text/javascript">
  $(".page-content").css({"margin-left": "0px"});
  $(".page-content").css({"background": "#37BC9B"})
</script>
<div class="login toolkits">
	<div class="login-wrapper">
		<%= form_tag(controller: "topcoder_profile", action: "create") do %>
		  	<div class="form-group has-feedback lg left-feedback no-label">
				<%= text_field_tag :handle, nil, class: "form-control no-border input-lg rounded", placeholder: "Handle" %>
				<span class="fa fa-envelope form-control-feedback"></span>
			</div>
			<div class="actions">
				<%= submit_tag "Go", class: "btn btn-warning btn-lg btn-perspective btn-block" %>
			</div>
		<% end %>
	</div>
</div>

app/views/topcoder_profile/show_tcp_profile.html.erb
<%= render partial: 'profiles/left_side_bar' %>
<div id="individual_profile">
	<%= render partial: 'show' %>
</div>
<%= render partial: 'profiles/ajax_links' %>

app/views/topcoder_profile/show_tcp_profile.js.erb
$('#individual_profile').html("<%= escape_javascript render(:partial => 'topcoder_profile/show')%>");