config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'profiles#index'
  get '/home', to: 'profiles#home', as: :home

  get '/profiles/search', to: 'profiles#search', as: :search_developer
  post '/profiles/search', to: 'profiles#search_filter', as: :search_developer_post
  
  get '/:username', to: 'profiles#show', as: :profile
  get '/users/edit_links', to: 'profiles#edit_links', as: :edit_links
  post '/users/update_links', to: 'profiles#update_links'

  get '/integrations/codeforces/new', to: 'codeforces_profile#new', as: :cfp_profile_new
  post '/integrations/codeforces/create', to: 'codeforces_profile#create'
  get '/integrations/codeforces/recent_submissions/:handle', to: 'codeforces_profile#recent_submissions', as: :cfp_submissions
  get '/integrations/codeforces/show/:username', to: 'codeforces_profile#show_cfp_profile', as: :cfp_show_profile
  get '/integrations/codeforces/update', to: 'codeforces_profile#update', as: :cfp_update_profile
  get '/integrations/codeforces/delete', to: 'codeforces_profile#delete', as: :cfp_delete_profile

  get '/integrations/edit', to: 'profiles#edit_integrations', as: :edit_integrations

  get '/integrations/github/create', to: 'github_profile#create', as: :github_profile_create
  get '/integrations/github/show/:username', to: 'github_profile#show', as: :github_show_profile
  get '/integrations/github/update', to: 'github_profile#update', as: :github_update_profile
  get '/integrations/github/delete', to: 'github_profile#delete', as: :github_delete_profile 

  get '/integrations/topcoder/new', to: 'topcoder_profile#new', as: :topcoder_profile_new
  post '/integrations/topcoder/create', to: 'topcoder_profile#create', as: :topcoder_profile_create
  get '/integrations/topcoder/show/:username', to: 'topcoder_profile#show_tcp_profile', as: :tcp_show_profile
  get '/integrations/topcoder/update', to: 'topcoder_profile#update', as: :topcoder_update_profile
  get '/integrations/topcoder_profile/delete', to: 'topcoder_profile#delete', as: :topcoder_delete_profile

  get '/integrations/linkedin/create', to: 'linkedin_profile#create', as: :linkedin_profile_create
  get '/integrations/linkedin/show/:username', to: 'linkedin_profile#show_profile', as: :linkedin_show_profile
  post '/integrations/linkedin/refine', to: 'linkedin_profile#refine', as: :linkedin_refine
  get '/integrations/linkedin/update', to: 'linkedin_profile#update', as: :linkedin_update_profile
  get '/integrations/linkedin/delete', to: 'linkedin_profile#delete', as: :linkedin_delete_profile 

  get '/mails/new/:username', to: 'mails#new', as: :new_mails
  post '/mails/send/:username', to: 'mails#send_mail', as: :send_mails
  get '/mails/delete/:id', to: 'mails#delete' , as: :delete_mails

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :authenticate_user!, only: [:edit_links, :update_links]

	def index
		if user_signed_in?
			redirect_to profile_path(current_user.username)
		else
			redirect_to :home
		end
	end

	def home
	end

	def show
		username = params[:username]
		@user = User.where(username: username).first
		if @user.nil?
			render file: 'public/404', status: 404, formats: [:html]
		else
			session[:viewed_profiles] = [] if session[:viewed_profiles].nil?
			@first_name = @user.full_name.split(" ").first

			@algo_langs = @user.algo_langs
			@application_langs = @user.application_langs
			@all_langs = @user.all_langs(@application_langs.dup, @algo_langs.dup)

			@github_profile = @user.github_profile
			@codeforces_profile = @user.codeforces_profile

			@linkedin_profile = @user.linkedin_profile
			unless @linkedin_profile.nil?
				@industry = @linkedin_profile.data["industry"]
			end
			if  not @user.nil? and not @user==current_user and not session[:viewed_profiles].include?(@user.id)
				view = @user.view_count+1
				session[:viewed_profiles] << @user.id
				@user.update_attributes(view_count: view)
			end
			respond_to do |format|
				format.js
				format.html
			end
		end
	end

	def edit_links
		current_user
		@website_link = current_user.website_link
		if @website_link.nil? then @website_link = "" else @website_link.url end

		if current_user.website_link.nil?
			@website_link = ""
		else
			@website_link = current_user.website_link.url
		end

		if current_user.blog_link.nil?
			@blog_link = ""
		else
			@blog_link = current_user.blog_link.url
		end

		if current_user.gplus_link.nil?
			@gplus_link = ""
		else
			@gplus_link = current_user.gplus_link.nurl
		end

		if current_user.facebook_link.nil?
			@facebook_link = ""
		else
			@facebook_link = current_user.facebook_link.nurl
		end

		if current_user.twitter_link.nil?
			@twitter_link = ""
		else
			@twitter_link = current_user.twitter_link.nurl
		end

		if current_user.quora_link.nil?
			@quora_link = ""
		else
			@quora_link = current_user.quora_link.url
		end

		if current_user.stack_link.nil?
			@stack_link = ""
		else
			@stack_link = current_user.stack_link.nurl
		end
	end

	def update_links
		logger.info(params)
		u = current_user
		params[:gplus_link] = GplusLink.normalize_url(params[:gplus_link])
		params[:facebook_link] = FacebookLink.normalize_url(params[:facebook_link])
		params[:twitter_link] = TwitterLink.normalize_url(params[:twitter_link])
		params[:stack_link] = StackLink.normalize_url(params[:stack_link])

		if not u.website_link.nil?
			u.website_link.url = params[:website_link]
			u.website_link.save!
		elsif params[:website_link]!=""
			WebsiteLink.create(user_id: u.id, url: params[:website_link])
		end

		if not u.blog_link.nil?
			u.blog_link.url = params[:blog_link]
			u.blog_link.save!
		elsif params[:blog_link]!=""
			BlogLink.create(user_id: u.id, url: params[:blog_link])
		end

		if not u.gplus_link.nil?
			u.gplus_link.url = params[:gplus_link]
			u.gplus_link.save!
		elsif params[:gplus_link]!=""
			GplusLink.create(user_id: u.id, url: params[:gplus_link])
		end

		if not u.facebook_link.nil?
			u.facebook_link.url = params[:facebook_link]
			u.facebook_link.save!
		elsif params[:facebook_link]!=""
			FacebookLink.create(user_id: u.id, url: params[:facebook_link])
		end

		if not u.twitter_link.nil?
			u.twitter_link.url = params[:twitter_link]
			u.twitter_link.save!
		elsif params[:twitter_link]!=""
			TwitterLink.create(user_id: u.id, url: params[:twitter_link])
		end

		if not u.quora_link.nil?
			u.quora_link.url = params[:quora_link]
			u.quora_link.save!
		elsif params[:quora_link]!=""
			QuoraLink.create(user_id: u.id, url: params[:quora_link])
		end

		if not u.stack_link.nil?
			u.stack_link.url = params[:stack_link]
			u.stack_link.save!
		elsif params[:stack_link]!=""
			StackLink.create(user_id: u.id, url: params[:stack_link])
		end

		redirect_to :root
	end

	def edit_integrations
	end

	def search
	end

	def search_filter
		if not params[:locations].nil? and not params[:locations].empty?
			locations = Location.all
			locs = locations.select {|l| params[:locations].any? { |s| l.name.include?(s) } }
			@users = locs.map{|l| l.users.to_a}.flatten
		else
			@users = User.all.to_a
		end

		@users = @users.select {|user| user.username.downcase.include?(params[:username].downcase) and user.full_name.downcase.include?(params[:name].downcase) }

		@skills_req = params[:skills]
		if not @skills_req.nil? and not @skills_req.empty?
			@users = @users.select {|user|
				lp = user.linkedin_profile
				if lp.nil?
					false
				elsif not lp.data["skills"].nil? && lp.data["skills"].include?(@skills_req)
					true
				else
					false
				end
			}
		end

		@languages_req = params[:languages]
		if not @languages_req.nil? and not @languages_req.empty?
			lang_users = Language.where(name: @languages_req).map{|l| l.users.to_a}.flatten
			@users = @users & lang_users
		end

		unless params[:availability]=="on"
			@users.select! { |u| u.availability }
		end

		respond_to do |format|
			format.js
		end
	end
end

app/views/profiles/_ajax_links.html.erb
<script type="text/javascript">
	$('#cfp_profile').click(function() {
		ajaxLoad("<%=cfp_show_profile_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=cfp_show_profile_path(username: @user.username)%>");
	});
	$('#tcp_profile').click(function() {
		ajaxLoad("<%=tcp_show_profile_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=tcp_show_profile_path(username: @user.username)%>");
	});
	$('#github_profile').click(function() {
		ajaxLoad("<%=github_show_profile_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=github_show_profile_path(username: @user.username)%>");
	});
	$('#linkedin_profile').click(function() {
		ajaxLoad("<%=linkedin_show_profile_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=linkedin_show_profile_path(username: @user.username)%>");
	});
	$('#edit_integrations').click(function() {
		ajaxLoad("<%=edit_integrations_path%>");
		window.history.pushState({},"", "<%=edit_integrations_path(username: @user.username)%>");
	});
	$('#contact').click(function() {
		ajaxLoad("<%=new_mails_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=new_mails_path(username: @user.username)%>");
	});
	$('#show_summary_link').click(function() {
		ajaxLoad("<%=profile_path(username: @user.username)%>");
		window.history.pushState({},"", "<%=profile_path(username: @user.username)%>");
	});
</script>

app/views/profiles/_edit_integrations.html.erb
<script type="text/javascript">
  $(".page-content").css({"margin-left": "0px"});
  $(".sidebar-left").hide();
// </script>
<h1 class="page-heading text-center" >Integrations</h1>
<hr>
<%- if Devise.mappings[:user].omniauthable? %>
<div class="row" id="github_edit">
	<%= render partial: "github_profile/edit" %>
</div>
<br>
<div class="row" id="linkedin_edit">
	<%= render partial: "linkedin_profile/edit" %>
</div>
<br>
 <% end -%>
<div class="row" id="codeforces_edit">
	<%= render partial: "codeforces_profile/edit" %>
</div>
<br>
<div class="row" id="topcoder_edit">
	
	<%= render partial: "topcoder_profile/edit" %>
</div>

app/views/profiles/_left_side_bar.html.erb
<div class="sidebar-left sidebar-nicescroller" style="width: 300px;">
			<div class="the-box no-border full card-info">
										<div class="the-box no-border text-center no-margin">
											<h4 class="bolded"><%= @user.full_name %></h4>
											<%= image_tag(@user.gravatar_url, class: "social-avatar has-margin has-light-shadow img-rounded") %>
											<p class="text-info">@<%= @user.username %></p>
											<% if @user.availability? %>
												<span class="label label-success">Available</span>
											<% else %>
												<span class="label label-warning">Unavailable</span>
											<% end %>
											<p class="text-muted short-bio">
												<%= @user.short_bio unless @user.short_bio.nil? %>
											</p>
											<% unless @user.location.nil? %>
												<p class="bordered"><i class="fa fa-map-marker"></i> <strong><%= @user.location.name %></strong></p>
											<% end%>
											<% unless @user.website_link.nil? %>
											<p>
												<a href="<%= @user.website_link.url %>" target="_blank">
													<%= @user.website_link.url %>
												</a>
											</p>
											<% end %>
											<p>
												<i class="glyphicon glyphicon-eye-open"></i>
												<Strong> <%= pluralize(@user.view_count, "View") %>
												</Strong>
											</p>
											<p class="social-icon">
												<% github_profile = @user.github_profile %>
												<% unless github_profile.nil? %>
													<a href="<%= github_link(github_profile.username) %>" target="_blank" data-toggle="links" data-placement="top" title="Github"><i class="fa fa-github icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% linkedin_profile = @user.linkedin_profile %>
												<% unless linkedin_profile.nil? %>
													<a href="<%= linkedin_link(linkedin_profile.uid) %>" target="_blank" data-toggle="links" data-placement="top" title="Linkedin"><i class="fa fa-linkedin icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% codeforces_profile = @user.codeforces_profile %>
												<% unless codeforces_profile.nil? %>
													<a href="<%= codeforces_link(codeforces_profile.handle) %>" target="_blank" data-toggle="links" data-placement="top" title="Codeforces"><i class="fa fa-cubes icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% topcoder_profile = @user.topcoder_profile %>
												<% unless topcoder_profile.nil? %>
													<a href="<%= topcoder_link(topcoder_profile.handle) %>" target="_blank" data-toggle="links" data-placement="top" title="Topcoder"><i class="fa fa-tumblr icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.stack_link.nil? %>
													<a href="<%= @user.stack_link.nurl %>" target="_blank" data-toggle="links" data-placement="top" title="StackOverFlow"><i class="fa fa-stack-overflow icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.blog_link.nil? %>
													<a href="<%= @user.blog_link.url %>" target="_blank" data-toggle="links" data-placement="top" title="Blog"><i class="fa fa-wordpress icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.gplus_link.nil? %>
													<a href="<%= @user.gplus_link.nurl %>" target="_blank" data-toggle="links" data-placement="top"title="Google+"><i class="fa fa-google-plus icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.facebook_link.nil? %>
													<a href="<%= @user.facebook_link.nurl %>" target="_blank" data-toggle="links" data-placement="top"title="Facebook"><i class="fa fa-facebook icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.twitter_link.nil? %>
													<a href="<%= @user.twitter_link.nurl %>" target="_blank" data-toggle="links" data-placement="top"title="Twitter"><i class="fa fa-twitter icon-xs icon-circle icon-default"></i></a>
												<% end %>
												<% unless @user.quora_link.nil? %>
													<a href="<%= @user.quora_link.url %>" target="_blank" data-toggle="links" data-placement="top"title="Quora"><i class="fa fa-reddit-square icon-xs icon-circle icon-default"></i></a>
												<% end %>
											</p>
										</div><!-- /.the-box .no-border .bg-info .no-margin -->

										<% if (not current_user.nil? and @user!=current_user)  %>
											<a href="<%= new_mails_path(@user.username) %>" class="btn btn-primary btn-block btn-lg btn-square" data-remote="true" id="contact"><i class="fa fa-user"></i> Contact</a>
										<% elsif current_user.nil? %>
											<a href="<%= new_user_session_path %>" class="btn btn-primary btn-block btn-lg btn-square" ><i class="fa fa-user"></i> Contact</a>
										<% end %>
									</div><!-- /.the-box -->
									<!-- END PROFILE CARD  -->
				<%= render partial: 'profiles/submenu' %>
				
			</div><!-- /.sidebar-left -->
			<!-- END SIDEBAR LEFT -->

<script type="text/javascript">
	$(".sidebar-nicescroller").niceScroll({
		cursorcolor: "#121212",
		cursorborder: "0px solid #fff",
		cursorborderradius: "0px",
		cursorwidth: "0px"
	});

	$('.sidebar-left ul.sidebar-menu li a').click(function() {
		"use strict";
		$('.sidebar-left li').removeClass('active');
		$(this).closest('li').addClass('active');	
		var checkElement = $(this).next();
			if((checkElement.is('ul')) && (checkElement.is(':visible'))) {
				$(this).closest('li').removeClass('active');
				checkElement.slideUp('fast');
			}
			if((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
				$('.sidebar-left ul.sidebar-menu ul:visible').slideUp('fast');
				checkElement.slideDown('fast');
			}
			if($(this).closest('li').find('ul').children().length == 0) {
				return true;
				} else {
				return false;	
			}		
	});

$(document).ready(function(){
	$(function () {
	  $('[data-toggle="links"]').tooltip();
	});
});
</script>

app/views/profiles/_search_filter.html.erb
<div class="sidebar-left sidebar-nicescroller" style="width: 300px;">
    <div class='the-box bg-dark no-border'>
      <div class='panel-heading'>
        <center><h4>Search</h4></center>
      </div>
      <section class='panel-body'>
        <div class='col-md-10 col-md-offset-1'>
        <form action="<%= search_developer_post_path %>" method="post" data-remote="true" id="search_dev">
          <div class='row form-group'>
            <label>Username</label>
            <input name="username" type="text" placeholder="Enter Title" class="form-control autocomplete">
          </div>
          <div class='row form-group'>
            <label>Name</label>
            <input name="name" type="text" placeholder="Enter Title" class="form-control autocomplete">
          </div>
          <div class="row form-group">
            <label>Location</label>
            <select name="locations[]" data-placeholder="City and/or country" class="form-control chosen-select" multiple>
              <% Location.all.each do |location| %>
                <option value="<%= location.name %>"><%= location.name %></option>
              <% end %>
            </select>
          </div>
          <div class="row form-group">
            <label>Languages</label>
            <select name="languages[]" data-placeholder="Choose language(s)" class="form-control chosen-select" multiple>
              <% Language.all.each do |language| %>
                <option value="<%= language.name %>"><%= language.name %></option>
              <% end %>
            </select>
          </div>
          <div class="row form-group">
            <label>Skills</label>
            <select name="skills[]" data-placeholder="Start typing skills!" class="form-control chosen-select" multiple>
              <% User.all_skills.each do |skill|%>
                <option value="<%=skill%>"><%=skill%></option>
              <% end %>
            </select>
          </div>
          <div class="row">
            <label> Check availability</label>
            <div class="onoffswitch blank">
              <input type="checkbox" name="availability" class="onoffswitch-checkbox" id="example-switch-1" checked>
              <label class="onoffswitch-label" for="example-switch-1">
                <span class="onoffswitch-inner"></span>
                <span class="onoffswitch-switch"></span>
              </label>
            </div>
          </div>
          <br/>
          <div class="row text-center">
            <button id="search_button" class="btn btn-info btn-block">GO!</button>
          </div>
          </form>
        </div>
      </section>
    </div>
</div>

<script type="text/javascript" src="/assets/chosen.jquery.min.js"></script> 
<script type="text/javascript">
    $(function () {
      "use strict";
      var configChosen = {
        '.chosen-select'           : {},
        '.chosen-select-deselect'  : {allow_single_deselect:true},
        '.chosen-select-no-single' : {disable_search_threshold:10},
        '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'},
        '.chosen-select-width'     : {width:"100%"}
      }
      for (var selector in configChosen) {
        $(selector).chosen(configChosen[selector]);
      }
    });

    $('#search_button').click(function() {
      NProgress.start();
      NProgress.inc();
      $('#search_dev').submit();
    });

    $(".sidebar-nicescroller").niceScroll({
      cursorcolor: "#121212",
      cursorborder: "0px solid #fff",
      cursorborderradius: "0px",
      cursorwidth: "0px"
    });
</script>

app/views/profiles/_submenu.html.erb
<ul class="sidebar-menu">
	<li>
		<a href="javascript:void(0);" id="show_summary_link"><i class="fa fa-dashboard icon-sidebar"></i>
		Profile
		<% if not @user.profile_updated_at.nil? %>	
			<% if not @user.profile_updated_at < 2.days.ago %>
				<span class="label label-success span-sidebar">UPDATED</span>
			<% end -%>
		<% end -%>
		</a>
	</li>
	<li >
		<a href= "#">
			<i class="fa fa-desktop icon-sidebar"></i>
			<i class="fa fa-angle-right chevron-icon-sidebar"></i>
			Projects
			</a>
		<ul class="submenu">
			<li><%= link_to "Github", "javascript:void(0);", id: 'github_profile' %></li>
			<li><%= link_to "LinkedIn", "javascript:void(0);", id: 'linkedin_profile' %></li>
		</ul>
	</li>
	<li>
		<a href="#">
			<i class="fa fa-flask icon-sidebar"></i>
			<i class="fa fa-angle-right chevron-icon-sidebar"></i>
			Programming
		</a>
		<ul class="submenu">
			<li><%= link_to "Codeforces", "javascript:void(0);", id: 'cfp_profile' %></li>
			<li><%= link_to "Topcoder", "javascript:void(0);", id: 'tcp_profile' %></li>
		</ul>
	</li>
	
	<% if not @user.profile_updated_at.nil? %>
		<li class="static text-center">Last updated on <%= @user.profile_updated_at.strftime("%B %d, %Y")%></li>
	<% end -%>
</ul>

app/views/profiles/home.html.erb
<script type="text/javascript">
	$(function() {
  $('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html,body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});

$("#header-id").remove();
$("body").css({"padding-top": "0px"});
$(".page-content").css({"margin-left": "0px"});
$(".page-content").css({"background": "black"});
</script>

<div class="row alpha_wrapper">
	<div id="alpha_2">
	</div><!-- alpha_2 ends -->
	<div id="text_holder_2">
        <div class="row">
            <div class="col-lg-12 col-sm-8 main-logo-container">
                <center>
                    <div class="main-logo">
                        <%= link_to image_tag("logo.png"), home_path %>
                    </div>
                </center>
            </div>
        </div>
        <div class="row">
        	<div class="col-lg-12">
                <center>
            		<p class="homepage-heading">
                    let your code speak for you
            		</p>	
                </center>
        	</div>
        </div>
    	<div class="row">
    		<div class="col-lg-4 col-lg-offset-2">
                <div class="row">
                    <div class="score-text text-center hm-text">
                         [Pro-logg]
                         <br/>
                         adj. & acronymn for Professoinal People
                         <br/>
                         origin: India
                    </div>
                </div>
                <div class="row">
                    <div class="text-center hm-button">
                        <% if user_signed_in? %>
                            <%= link_to "Your Profile", profile_path(current_user.username), class: "btn btn-lg btn-info", style: "color: black;" %>
                        <% else %>
                            <%= link_to "Sign-in", new_user_session_path, class: "btn btn-lg btn-info", style: "color: black;" %>
                        <% end %>
                    </div>
                </div>
    		</div> 
        	<div class="col-lg-4 col-lg-offset-1">
                <div class="row">
            		<div class="score-text text-center hm-text">
    				    Track your daily progress.
                        <br/>
                        Analyze and enhance your skills. 
                        <br/>
                        Because we speak for you.
     				 </div>
                </div>
                <div class="row">
                    <div class="text-center hm-button">
                        <% if user_signed_in? %>
                            <%= link_to "Search a companion", search_developer_path, class: "btn btn-lg btn-info", style: "color: black;" %>
                        <% else %>
                            <%= link_to "Register", new_user_registration_path, class: "btn btn-lg btn-info", style: "color: black;" %>
                        <% end %>
                    </div>
                </div>
        	</div>
    	</div>
        <div class="last-row arrow-1">
            <div class="col-lg-4 col-lg-offset-4">
                <center>
            		<a href="#three">
            		<i class="fa fa-chevron-down icon-lg"></i></a>
                </center>
        	</div>
    	</div>
	</div>
</div>
<div class="row" id="three" style="background-color : #242A34 ">
	<div class="col-lg-12 main-logo-container">
        <center>
            <div class="main-logo">
                <%= link_to image_tag("logo.png"), home_path %>
            </div>
        </center>
    </div>
	<div class="col-lg-12">
        <center>
    		<p class = "homepage-heading row">
                An entire hub for Developers
            </p>
        </center>
	</div>
    <div class="row">
        <center>
            <%= link_to "Search Developers", search_developer_path, class: "btn btn-lg btn-success", style: "color: black;" %>
        </center>
    </div>
	<div class="row">
    	<ul id="UL_1">
        <div class="col-lg-11 col-lg-offset-1">
        	<div class="col-lg-4">
            	<li id="LI_2">
            		<div id="DIV_3">
            			 <span id="SPAN_4"><img alt="People" src="https://d3keuzeb2crhkn.cloudfront.net/hackerrank/assets/people-95ead8799bad0f6f790e1c4b07e59faf.png" id="IMG_5" />
            			 <div style="margin-top:25px">
            			 	<%= User.all.count %> Developers
            			 </div>
            			 </span>
            		</div>
            	</li>
        	</div>
        	<div class="col-lg-4">
            	<li id="LI_8">
            		<div id="DIV_9">
            			 <span id="SPAN_10"><img alt="Python-logo" src="https://d3keuzeb2crhkn.cloudfront.net/hackerrank/assets/python-logo-3ecf8d0c174f0206c25d2a084ee898ef.png" id="IMG_11" />
            			 <div style="margin-top:25px">
            			 	<%= Language.all.count %> Languages
            			 </div>
            			 </span>
            		</div>
            	</li>
        	</div>
        	<div class="col-lg-4">
            	<li id="LI_14">
            		<div id="DIV_15">
            			 <span id="SPAN_16"><img alt="Medal_of_honor" src="https://d3keuzeb2crhkn.cloudfront.net/hackerrank/assets/medal_of_honor-82477001d4cc45c954cf89f98d2ea4f1.png" id="IMG_17" />
            			 <div style="margin-top:25px">
            			 	4 Integrations
            			 </div></span>
            		</div>
            	</li>
        	</div>
        </div>
        </ul>
	</div>
	<div class="last-row arrow-2">
        <div class="col-lg-4 col-lg-offset-4">
            <center>
                <a href="#four">
                <i class="fa fa-chevron-down icon-lg"></i></a>
            </center>
        </div>
    </div>
</div>

<div class="row" id="four">
	<div id="alpha_3">
	</div><!-- alpha_2 ends -->
	<div id="text_holder_2">
        <div class="row">
            <div class="col-lg-12 col-sm-8 main-logo-container">
                <center>
                    <div class="main-logo">
                        <%= link_to image_tag("logo.png"), home_path %>
                    </div>
                </center>
            </div>
        </div>
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
                <div class="videoWrapper">
                    <!-- Copy & Pasted from YouTube -->
                    <iframe width="560" height="349" src="https://www.youtube.com/embed/AK5tbJaNzLA?rel=0&hd=1" frameborder="0" allowfullscreen></iframe>
                </div> 
			</div>
		</div>
	</div>
</div>

app/views/profiles/search_filter.js.erb
$('#search_results').html("<%= escape_javascript render(:partial => 'results')%>");
NProgress.done();

app/views/profiles/show.html.erb
<%= render partial: 'left_side_bar' %>
<div id="individual_profile">
	<%= render partial: 'show_summary' %>
</div>
<%= render partial: 'profiles/ajax_links' %>

app/views/profiles/show.js.erb
$('#individual_profile').html("<%= escape_javascript render(:partial => 'show_summary') %>");