config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'profiles#index'
  get '/home', to: 'profiles#home', as: :home

  get '/profiles/search', to: 'profiles#search', as: :search_developer
  post '/profiles/search', to: 'profiles#search_filter', as: :search_developer_post
  
  get '/:username', to: 'profiles#show', as: :profile
  get '/users/edit_links', to: 'profiles#edit_links', as: :edit_links
  post '/users/update_links', to: 'profiles#update_links'

  get '/integrations/codeforces/new', to: 'codeforces_profile#new', as: :cfp_profile_new
  post '/integrations/codeforces/create', to: 'codeforces_profile#create'
  get '/integrations/codeforces/recent_submissions/:handle', to: 'codeforces_profile#recent_submissions', as: :cfp_submissions
  get '/integrations/codeforces/show/:username', to: 'codeforces_profile#show_cfp_profile', as: :cfp_show_profile
  get '/integrations/codeforces/update', to: 'codeforces_profile#update', as: :cfp_update_profile
  get '/integrations/codeforces/delete', to: 'codeforces_profile#delete', as: :cfp_delete_profile

  get '/integrations/edit', to: 'profiles#edit_integrations', as: :edit_integrations

  get '/integrations/github/create', to: 'github_profile#create', as: :github_profile_create
  get '/integrations/github/show/:username', to: 'github_profile#show', as: :github_show_profile
  get '/integrations/github/update', to: 'github_profile#update', as: :github_update_profile
  get '/integrations/github/delete', to: 'github_profile#delete', as: :github_delete_profile 

  get '/integrations/topcoder/new', to: 'topcoder_profile#new', as: :topcoder_profile_new
  post '/integrations/topcoder/create', to: 'topcoder_profile#create', as: :topcoder_profile_create
  get '/integrations/topcoder/show/:username', to: 'topcoder_profile#show_tcp_profile', as: :tcp_show_profile
  get '/integrations/topcoder/update', to: 'topcoder_profile#update', as: :topcoder_update_profile
  get '/integrations/topcoder_profile/delete', to: 'topcoder_profile#delete', as: :topcoder_delete_profile

  get '/integrations/linkedin/create', to: 'linkedin_profile#create', as: :linkedin_profile_create
  get '/integrations/linkedin/show/:username', to: 'linkedin_profile#show_profile', as: :linkedin_show_profile
  post '/integrations/linkedin/refine', to: 'linkedin_profile#refine', as: :linkedin_refine
  get '/integrations/linkedin/update', to: 'linkedin_profile#update', as: :linkedin_update_profile
  get '/integrations/linkedin/delete', to: 'linkedin_profile#delete', as: :linkedin_delete_profile 

  get '/mails/new/:username', to: 'mails#new', as: :new_mails
  post '/mails/send/:username', to: 'mails#send_mail', as: :send_mails
  get '/mails/delete/:id', to: 'mails#delete' , as: :delete_mails

end

app/models/codeforces_profile.rb
class CodeforcesProfile < ActiveRecord::Base
	belongs_to :user

	def self.get(url)
		begin
			resp = RestClient.get(url)
			return JSON.parse(resp)
		rescue
			return {"status" => "bad_request"}
		end
	end

	def self.connect(handle)
		url = "http://codeforces.com/api/user.info?handles=#{handle}"
		resp = self.get(url)
		return [resp["status"], resp]
	end

	def self.get_submissions(handle)
		url = "http://codeforces.com/api/user.status?handle=#{handle}&from=1&count=1000"
		resp = self.get(url)
		return [resp["status"], resp]
	end

	def self.get_ratings(handle)
		url = "http://codeforces.com/api/user.rating?handle=#{handle}"
		resp = self.get(url)
		return [resp["status"], resp]
	end

	def self.get_recent_submissions(handle)
		url = "http://codeforces.com/api/user.status?handle=#{handle}&from=1&count=8"
		resp = self.get(url)
		return [resp["status"], resp]
	end

	def self.problems_lang_tags(resp_subs)
		solved_probs = 0		#total number of problems solved
		langs = {}				#hash of hashes - languages => no of problems solved
		tags_count = {}			#hash of hashes - tags => total no. of problems in which it is found.
		resp_subs.select do |h|
			if h["verdict"]=="OK"
				if langs.key?(h["programmingLanguage"])
					langs.merge!(h["programmingLanguage"] => langs[h["programmingLanguage"].to_s] + 1)
				else
					langs.merge!(h["programmingLanguage"] => 1)
				end
				tags = h["problem"]["tags"]
				tags.each do |tag|
					if tags_count.key?(tag)
						tags_count.merge!(tag => tags_count[tag] + 1)
					else
						tags_count.merge!(tag => 1)
					end
				end
				solved_probs = solved_probs + 1
			end
		end

		tags_count = tags_count.to_a.sort_by {|tag| tag[1]}.reverse.to_h
		langs = langs.to_a.sort_by {|lang| lang[1]}.reverse.to_h

		return [solved_probs, tags_count, langs]
	end

	def self.ratings(resp_rates)
		resp_rates.each do |h|
			h.delete("contestId")
			h.delete("contestName")
			h.delete("rank")
		end
		resp_rates.slice!(resp_rates.length-4..resp_rates.length)
		resp_rates
	end
end

app/controllers/codeforces_profile_controller.rb
class CodeforcesProfileController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :create, :update]
	protect_from_forgery except: :recent_submissions

	def new
	end

	def create
		handle = params[:handle]

		begin
			response_info = CodeforcesProfile.connect(handle)
			status_info = response_info[0]

			if status_info == "OK"

				response_subs = CodeforcesProfile.get_submissions(handle)
				status_subs = response_subs[0]

				response_rates = CodeforcesProfile.get_ratings(handle)
				status_rates = response_rates[0]

				if status_subs == "OK" and status_rates == "OK"

					resp_info = response_info[1]["result"][0]
					resp_subs = response_subs[1]["result"]
					resp_rates = response_rates[1]["result"]

					@codeforces_profile = CodeforcesProfile.new(
						user_id: current_user.id,
						handle: resp_info["handle"]
					)

					data1 = CodeforcesProfile.problems_lang_tags(resp_subs)
					solved_probs = data1[0]			#total number of problems solved
					tags_count = data1[1]			#hash of hashes - tags => total no. of problems in which it is found.
					langs = data1[2]				#hash of hashes - languages => no of problems solved

					database_langs = Language.all.map(&:name)
					user_database_langs = current_user.languages.map(&:name)
					langs.keys.each do |lang|
						if database_langs.include?(lang)
							unless user_database_langs.include?(lang)
								existing_lang = Language.where(name: lang).first
								current_user.languages << existing_lang
							end
						else
							new_lang = Language.create(name: lang)
							current_user.languages << new_lang
						end
					end

					#Update Last updated at attribute
					current_user.profile_updated_at = Time.now
					current_user.save!
					current_user.reload

					resp_rates = CodeforcesProfile.ratings(resp_rates)

					resp_info["firstName"] = "" if resp_info["firstName"].nil?
					resp_info["lastName"] = "" if resp_info["lastName"].nil?

					@codeforces_profile.data = {
													solved_probs: solved_probs,
													languages: langs,
													tags: tags_count,
													ratings: resp_rates,
													handle: resp_info["handle"],
													contribution: resp_info["contribution"],
													rank: resp_info["rank"],
													max_rank: resp_info["maxRank"],
													rating: resp_info["rating"],
													max_rating: resp_info["maxRating"],
													last_online: DateTime.strptime(resp_info["lastOnlineTimeSeconds"].to_s, '%s'),
													real_name: [resp_info["firstName"], resp_info["lastName"]].join(" ").strip
												}
					@codeforces_profile.save!

					flash[:notice] = "You have successfully integrated Codeforces in your profile."
					redirect_to profile_path(username: current_user.username)
				else
					flash[:alert] = "It seems your credentials are not authentic or something went wrong."
					redirect_to :back
				end
			else
				flash[:alert] = "It seems your credentials are not authentic or something went wrong. Try again after sometime."
				redirect_to :back
			end
		rescue Exception => e
			cfp = current_user.codeforces_profile
			unless cfp.nil?
				cfp.destroy
			end
			current_user.reload
			flash[:alert] = "It seems your credentials are not authentic or something went wrong. Try again after sometime."
			redirect_to :back
		end
	end

	def update
		@codeforces_profile = current_user.codeforces_profile
		old_data = @codeforces_profile.data

		if @codeforces_profile.nil?
			flash[:alert] = "You don't have Codeforces account integrated with your profile."
			redirect_to :back
		else
			handle = @codeforces_profile.handle

			begin
				response_info = CodeforcesProfile.connect(handle)
				status_info = response_info[0]
				resp_info = response_info[1]["result"][0]

				if status_info == "OK"
					new_last_online = DateTime.strptime(resp_info["lastOnlineTimeSeconds"].to_s, '%s')

					if @codeforces_profile.data["last_online"] < new_last_online

						response_subs = CodeforcesProfile.get_submissions(handle)
						status_subs = response_subs[0]
						resp_subs = response_subs[1]["result"]

						response_rates = CodeforcesProfile.get_ratings(handle)
						status_rates = response_rates[0]
						resp_rates = response_rates[1]["result"]

						if status_subs == "OK" and status_rates == "OK"

							data1 = CodeforcesProfile.problems_lang_tags(resp_subs)
							solved_probs = data1[0]			#total number of problems solved
							tags_count = data1[1]			#hash of hashes - tags => total no. of problems in which it is found.
							langs = data1[2]				#hash of hashes - languages => no of problems solved

							database_langs = Language.all.map(&:name)
							user_database_langs = current_user.languages.map(&:name)
							langs.keys.each do |lang|
								if database_langs.include?(lang)
									unless user_database_langs.include?(lang)
										existing_lang = Language.where(name: lang).first
										current_user.languages << existing_lang
									end
								else
									new_lang = Language.create(name: lang)
									current_user.languages << new_lang
								end
							end

							#Update Last updated at attribute
							current_user.profile_updated_at = Time.now
							current_user.save!
							current_user.reload

							resp_rates = CodeforcesProfile.ratings(resp_rates)

							@codeforces_profile.data = {
													solved_probs: solved_probs,
													languages: langs,
													tags: tags_count,
													ratings: resp_rates,
													handle: resp_info["handle"],
													contribution: resp_info["contribution"],
													rank: resp_info["rank"],
													max_rank: resp_info["maxRank"],
													rating: resp_info["rating"],
													max_rating: resp_info["maxRating"],
													last_online: DateTime.strptime(resp_info["lastOnlineTimeSeconds"].to_s, '%s'), 
													real_name: [resp_info["firstName"], resp_info["lastName"]].join(" ").strip
												}
							@codeforces_profile.data_will_change!
							@codeforces_profile.save!
							flash[:notice] = "Successfully updated your Codeforces profile!"
							redirect_to profile_path(username: current_user.username)
						else
							flash[:alert] = "It seems your credentials are not authentic or something went wrong."
							redirect_to :back
						end
					else
						flash[:notice] = "Your Codeforces profile is already upto date."
						redirect_to :back
					end
				else
					flash[:alert] = "It seems your credentials are not authentic or something went wrong."
					redirect_to :back
				end
			rescue Exception => e
				@codeforces_profile.data = old_data
				@codeforces_profile.data_will_change!
				@codeforces_profile.save!
				current_user.reload
				flash[:alert] = "It seems your credentials are not authentic or something went wrong."
				redirect_to :back
			end
		end
	end

	def recent_submissions
		handle = params[:handle]

		begin
			response = CodeforcesProfile.get_recent_submissions(handle)
			status = response[0]

			if status=="OK"
				@resp = response[1]["result"].paginate(page: params[:page], per_page: 4)
				@resp.each do |sub|
					sub.select! {|k,v| ["problem", "programmingLanguage", "creationTimeSeconds", "verdict"].include?(k) }
					sub["problem"].select! { |k,v| ["name"].include?(k) }
				end
				respond_to do |format|
					format.js
				end
			else
				render js: ""
			end
		rescue Exception => e
			render js: ""
		end
	end

	def show_cfp_profile
		@user = User.where(username: params[:username]).first
		if @user.nil?
			render file: 'public/404', status: 404, formats: [:html]
		else
			@cfp = @user.codeforces_profile
			respond_to do |format|
				format.js
				format.html
			end
		end
	end

	def delete
		unless current_user.codeforces_profile.nil?
			CodeforcesProfile.where(:user => current_user).first.destroy
	 		current_user.save!
	 		current_user.reload
	 	end
		respond_to do |format|
			format.js
		end	
	end

end

app/views/codeforces_profile/_add_codeforces.html.erb
<% if @user == current_user %>
<div class="row" style="margin-top: 20px; margin-left: 25%; margin-bottom: 20px;">
	<strong>You have not integrated Codeforces Profile. You can Integrate it from below link.</strong>
</div>
	<div class="row">
	<div class="col-lg-6 col-lg-offset-2">
		<%= image_tag("codeforces_small.jpg", class: "sitelogo", style: "width: 50px; height: 50px;") %>
			&nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Codeforces</strong>
	</div>
	<div class="col-lg-4">
		<a href="<%= cfp_profile_new_path %>" class="btn btn-info btn-perspective"><i class="fa fa-plus-circle"></i>Add</a>&nbsp;
	</div>
</div>
<% else %>
	<div class="row" style="margin-top: 20px; margin-left: 25%; margin-bottom: 20px;"> 
	<strong><h3><%= @user.username %> has not integrated Codeforces profile.</h3> </strong>
	</div>
<% end -%>

app/views/codeforces_profile/_edit.html.erb
<div class="col-lg-6 col-lg-offset-2">
	<%= image_tag("codeforces_small.jpg", class: "sitelogo", style: "width: 50px; height: 50px;") %> &nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Codeforces</strong>
</div>
<div class="col-lg-4">
	<% if current_user.codeforces_profile.nil? %>
	<a href="<%= cfp_profile_new_path %>" class="btn btn-info btn-perspective"><i class="fa fa-plus-circle"></i>Add</a>&nbsp;
	<% else %>
	<a href="<%= cfp_update_profile_path %>" class="btn btn-success btn-perspective"><i class="fa fa-pencil-square-o"></i>Update</a>
	<a href="javascript:void(0);"  class="btn btn-danger btn-perspective" id= "delete_codeforces"><i class="fa fa-minus-circle"></i>Remove</a>&nbsp;
	<% end -%>
</div>

 <script type='text/javascript'>
		$(document).ready(function() {
		  	$('#delete_codeforces').on("click",function(){
				ajaxLoad("<%= cfp_delete_profile_path %>");
		  	});
		});
</script>

app/views/codeforces_profile/_recent_submissions.html.erb
<div class="col-lg-12">
	<div class="full no-border">
		<div class="table-responsive">
			<% unless @resp.empty? %>
				<div class="paginate_ajax">
					<table class="table table-th-block table-primary">
						<thead>
							<tr><th style="width: 30px;">No.</th><th>Problem</th><th>Programming Language</th><th>Date of submission</th><th>Status</th></tr>
						</thead>
						<tbody>
							<% i = 1 %>
							<% @resp.first(8).each do |item| %>
							<tr><td><%= i %></td><td><%= item["problem"]["name"] %></td><td><%= item["programmingLanguage"] %></td><td> <%= Time.at(item["creationTimeSeconds"]).to_date %></td><td><span class="label label-<%= color_status(item["verdict"]) %>"><%= item["verdict"] %></span></td></tr>
							<% i = i + 1 %>
							<% end -%>
						</tbody>
					</table>
					<%= will_paginate @resp, style: "margin-left: 15px;" %>
				</div>
			<% else %>
				<p> No submissions </p>
			<% end %>
		</div><!-- /.table-responsive -->
	</div>
</div>

app/views/codeforces_profile/_show.html.erb
<% if not @cfp.nil? %>
<!-- Begin page heading -->
<!-- End page heading -->
<!-- <div class = "directionlinestyle">
	<div style="margin-left : 15px; font-size : 15px;">
		<a href="homepage.html"> Home </a>
		<i class="fa fa-chevron-right"></i>
		<a href="homepage.html"> Programming </a>
		<i class="fa fa-chevron-right"></i>
		<a href="homepage.html"> Codeforces </a>
	</div>
	<hr class="seperator">
</div> -->
<!-- direction line ends here -->

<div class="logoline row">
	<!-- <img src="images.jpg" class="codeforcelogo" > -->
	<div class="col-lg-3">
		<%= image_tag("codeforces_small.jpg", class: "sitelogo", style: "width: 50px; height: 50px; margin-top: 10px;") %> &nbsp;&nbsp;&nbsp; <strong style="font-size: 30px;">Codeforces</strong>
	</div>
	<div class="col-lg-9 text-center panel-no-border panel-success panel-block-color panel-square">
		<div class="panel-heading">
			<h4 class="panel-title"> @<%= @cfp.handle.downcase %> </h4>
		</div>
		<div class="panel-body bg-success">
			<p>  (Last seen on <%= @cfp.data["last_online"] %>)  </p>
		</div>
	</div>
	<div class="col-lg-3">
		
	</div>
</div>

<!-- <hr class="seperator" style ="margin-top:5px;"> -->
<!-- current stat starts -->
<div class="row">
	<div class="col-lg-6">
		
		<div class="alert alert-warning alert-block square fade in alert-dismissable" data-toggle="code_rank" data-placement="top" title="Due to unavailability of Codeforces authentication system and user's email">
		  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
		  <p><strong>Warning!</strong></p>
		  <p>This account is unverifed 
		  <% if not @cfp.data["real_name"].nil? and not @cfp.data["real_name"].empty? %>
		  and belongs to <%= @cfp.data["real_name"] %>
		  <% end %>.
		  </p>
		</div>
		<!-- BEGIN WEATHER WIDGET 2 -->
		<div class="panel panel-info panel-square panel-no-border">
		  <div class="panel-heading">
			<div class="col-lg-6 text-center">
			  	PROBLEMS SOLVED
			  </div>
			  
			  <div class="col-lg-6 text-center" data-toggle="code_rank" data-placement="top" title="Problem statements created">
			  	CONTRIBUTIONS MADE
			  </div>
			</div>
		  	<div class="panel-body bg-info">
				<div class="row">
					<div class="col-sm-14">
						<div class="weather-widget horizontal">
							<div class="row">
								<div class="col-xs-6 text-center">
									  <span class="fa fa-code" style="
									    font-size: 50px;
									"></span>
									<p class="white-text" style="
									    font-size: 50px;
									"><%= @cfp.data["solved_probs"] %></p>
								</div><!-- /.col-xs-6 -->
								<div class="col-xs-6 text-center">
									  <span class="fa fa-puzzle-piece" style="
									    font-size: 50px;
									"></span>
									<p class="white-text" style="
									    font-size: 50px;
									"><%= @cfp.data["contribution"] %></p>
								</div><!-- /.col-xs-6 -->
							</div><!-- /.row -->
						</div><!-- /.weather-widget -->
					</div>
				</div><!-- /.row -->
		  	</div><!-- /.panel-body -->
		</div><!-- /.panel panel-success panel-block-color -->
		<!-- END WEATHER WIDGET 2 -->
		
	</div>

	<div class="col-lg-6">
		<div class="row">
			
			<div class="col-lg-6">
				
				<!-- BEGIN TODAY VISITOR TILES -->
				<div class="panel panel-danger panel-square panel-no-border text-center" data-toggle="code_rank" data-placement="top" title="<%=codeforces_tt( @cfp.data['rank'])%>">
				  <div class="panel-heading">
					<h3 class="panel-title">CURRENT RANKING</h3>
				  </div>
				  <div class="panel-body">
					<% unless @cfp.data["rank"].nil? %>
						<h2 class="bolded tiles-number text-danger"><%= @cfp.data["rank"].capitalize %></h1>
					<% else %>
						<h2 class="bolded tiles-number text-danger">Not Ranked</h1>
					<% end %>
				  </div><!-- /.panel-body -->
				</div><!-- /.panel panel-success panel-block-color -->
				<!-- END TODAY VISITOR TILES -->
				
			</div><!-- /.col-sm-6 -->
			<div class="col-lg-6">
				
				<!-- BEGIN TODAY VISITOR TILES -->
				<div class="panel panel-warning panel-square panel-no-border text-center">
				  <div class="panel-heading">
					<h3 class="panel-title">CURRENT RATING</h3>
				  </div>
				  <div class="panel-body">
					<% unless @cfp.data["rating"].nil? %>
						<h2 class="bolded tiles-number text-warning"><%= @cfp.data["rating"] %></h1>
					<% else %>
						<h2 class="bolded tiles-number text-danger">Unrated</h1>
					<% end %>
				  </div><!-- /.panel-body -->
				</div><!-- /.panel panel-success panel-block-color -->
				<!-- END TODAY VISITOR TILES -->
				
			</div><!-- /.col-sm-6 -->
		</div>
		<div class="row">
			<div class="col-lg-6">
				
				<!-- BEGIN TODAY VISITOR TILES -->
				<div class="panel panel-danger panel-square panel-no-border text-center" data-toggle="code_rank" data-placement="top" title="<%=codeforces_tt( @cfp.data['max_rank'])%>">
				  <div class="panel-heading">
					<h3 class="panel-title">MAX RANKING</h3>
				  </div>
				  <div class="panel-body">
					<% unless @cfp.data["rank"].nil? %>
						<h2 class="bolded tiles-number text-danger"><%= @cfp.data["max_rank"].capitalize %></h1>
					<% else %>
						<h2 class="bolded tiles-number text-danger">Not Ranked</h1>
					<% end %>
				  </div><!-- /.panel-body -->
				</div><!-- /.panel panel-success panel-block-color -->
				<!-- END TODAY VISITOR TILES -->
				
			</div><!-- /.col-sm-6 -->
			<div class="col-lg-6">
				
				<!-- BEGIN TODAY VISITOR TILES -->
				<div class="panel panel-warning panel-square panel-no-border text-center">
				  <div class="panel-heading">
					<h3 class="panel-title">MAX RATING</h3>
				  </div>
				  <div class="panel-body">
					<% unless @cfp.data["rank"].nil? %>
						<h2 class="bolded tiles-number text-warning"><%= @cfp.data["max_rating"] %></h1>
					<% else %>
						<h2 class="bolded tiles-number text-danger">Unrated</h1>
					<% end %>
				  </div><!-- /.panel-body -->
				</div><!-- /.panel panel-success panel-block-color -->
				<!-- END TODAY VISITOR TILES -->
				
			</div><!-- /.col-sm-6 -->
		</div>
	</div>
</div>
<!-- currentstat ends here -->

<div class="row">
	<div class="col-lg-6">
		<div class="the-box no-border" data-toggle="code_rank" data-placement="top" title="Shows user's congnitive interest and strength">
		<h4 class="small-title">Tags on Problem solved</h4>
		<% if @cfp.data["tags"].empty? %>
			<div style="height:100px;">
				User has not solved enough problems.
			</div>
		<% else %>
			<div style="height:252px; overflow-y:scroll;">
					<% @cfp.data["tags"].each_with_index do |key, index|%>
					<p class="small"><%= key[0].capitalize %>- <span class="text-<%= color(index+1) %>"><%= key[1]%></span></p>
					<div class="progress no-rounded progress-xs">
						<div class="progress-bar progress-bar-<%= color(index+1) %>" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: <%= key[1]*100/@cfp.data["solved_probs"] %>%">
						</div><!-- /.progress-bar .progress-bar-danger -->
					</div><!-- /.progress .no-rounded -->
				<% end -%>
			</div>
		<% end %>
		</div>
	</div>

	<div class="col-lg-6">
		<div class="the-box no-border">
			<h4 class="small-title">Problems solved in different Languages</h4>
			<% if @cfp.data["languages"].empty? %>
				<div style="height:100px;">
					User has not solved enough problems.
				</div>
			<% else %>
				<div id="morris-bar-example" style="height: 250px;"></div>
			<% end %>
		</div><!-- .the-box  -->
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="the-box no-border">
			<h4 class="small-title">Ratings (change accounted from recent contests)</h4>
			<% if @cfp.data["ratings"].empty? %>
				<div style="height:100px;">
					User has not participated in enough competitions.
				</div>
			<% else %>
				<div id="morris-line-example" style="height: 250px;"></div>
			<% end %>
		</div>
	</div>
</div>

<div class = "row">
	<div class="col-lg-12">
		<div class="the-box no-border">
			<div style="font-size : 15px; margin-bottom :  10px">
				<h4 class="small-title">Recently Submitted Problems</h4>
				<%= link_to "see Recent Submissions", "javascript:void(0);", {id: "cfp_rec_subs", class: "btn btn-primary btn-sm" } %>
			</div>
			<div id="recent_subs" class="row">
			</div>
		</div>
	</div>
	<hr class="seperator">
</div>

<% unless @cfp.data["ratings"].empty? %>
	<script type="text/javascript">
		/********************************* BEGIN EXAMPLE MORRIS LINE *********************************/
		Morris.Line({
		  element: 'morris-line-example',
		  data: [
		  	<% for item in @cfp.data["ratings"] %>
		  		{ y: '<%= Time.at(item["ratingUpdateTimeSeconds"]).to_date.strftime("%Y-%m-%d") %>', a: <%= item["newRating"] %>},
		  	<% end -%>
		  ],
		  xkey: 'y',
		  ykeys: ['a'],
		  labels: ['Rating'],
		  resize: true,
		  lineColors: ['#8CC152', '#F6BB42']
		});
		/********************************* END EXAMPLE MORRIS LINE *********************************/
	</script>
<% end %>

<% unless @cfp.data["languages"].empty? %>
	<script>
		/********************************* BEGIN EXAMPLE MORRIS BAR *********************************/
		Morris.Bar({
		  element: 'morris-bar-example',
		  data: [
		  	<% @cfp.data["languages"].each_with_index do |key, index| %>
		  		{ y: '<%= key[0] %>', a: <%= key[1] %>},
		  	<% end -%>
		  ],
		  xkey: 'y',
		  ykeys: ['a'],
		  labels: ['Problems solved'],
		  resize: true,
		  barColors: ['#3BAFDA', '#8CC152']
		});
		/********************************* END EXAMPLE MORRIS BAR *********************************/
	</script>
<% end %>

<script type="text/javascript">
	$('#cfp_rec_subs').click(function() {
		ajaxLoad("<%=cfp_submissions_path(handle: @cfp.handle)%>");
	});
</script>
<% else %>
	<%= render partial: 'add_codeforces' %>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $(function () {
      $('[data-toggle="code_rank"]').tooltip();
    });
  });
</script>

app/views/codeforces_profile/delete.js.erb
$('#codeforces_edit').html("<%= escape_javascript render(:partial => 'edit') %>");

app/views/codeforces_profile/new.html.erb
<script type="text/javascript">
  $(".page-content").css({"margin-left": "0px"});
  $(".page-content").css({"background": "#37BC9B"})
</script>
<div class="login toolkits">
	<div class="login-wrapper">
		<%= form_tag(controller: "codeforces_profile", action: "create") do %>
		  	<div class="form-group has-feedback lg left-feedback no-label">
				<%= text_field_tag :handle, nil, class: "form-control no-border input-lg rounded", placeholder: "Handle" %>
				<span class="fa fa-envelope form-control-feedback"></span>
			</div>
			<div class="actions">
				<%= submit_tag "Go", class: "btn btn-warning btn-lg btn-perspective btn-block" %>
			</div>
		<% end %>
	</div>
</div>

app/views/codeforces_profile/recent_submissions.js.erb
$('#recent_subs').html("<%= escape_javascript render(:partial => 'recent_submissions')	 %>");
$('#cfp_rec_subs').attr("href", "javascript:void(0);");
$(function() {
  $(".paginate_ajax th a, .paginate_ajax .pagination a").on("click", function(){
    $.getScript(this.href);
    return false;
  });
});

app/views/codeforces_profile/show_cfp_profile.html.erb
<%= render partial: 'profiles/left_side_bar' %>
<div id="individual_profile">
	<%= render partial: 'show' %>
</div>
<%= render partial: 'profiles/ajax_links' %>

app/views/codeforces_profile/show_cfp_profile.js.erb
$('#individual_profile').html("<%= escape_javascript render(:partial => 'codeforces_profile/show')	 %>");