config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: 'profiles#index'
  get '/home', to: 'profiles#home', as: :home

  get '/profiles/search', to: 'profiles#search', as: :search_developer
  post '/profiles/search', to: 'profiles#search_filter', as: :search_developer_post
  
  get '/:username', to: 'profiles#show', as: :profile
  get '/users/edit_links', to: 'profiles#edit_links', as: :edit_links
  post '/users/update_links', to: 'profiles#update_links'

  get '/integrations/codeforces/new', to: 'codeforces_profile#new', as: :cfp_profile_new
  post '/integrations/codeforces/create', to: 'codeforces_profile#create'
  get '/integrations/codeforces/recent_submissions/:handle', to: 'codeforces_profile#recent_submissions', as: :cfp_submissions
  get '/integrations/codeforces/show/:username', to: 'codeforces_profile#show_cfp_profile', as: :cfp_show_profile
  get '/integrations/codeforces/update', to: 'codeforces_profile#update', as: :cfp_update_profile
  get '/integrations/codeforces/delete', to: 'codeforces_profile#delete', as: :cfp_delete_profile

  get '/integrations/edit', to: 'profiles#edit_integrations', as: :edit_integrations

  get '/integrations/github/create', to: 'github_profile#create', as: :github_profile_create
  get '/integrations/github/show/:username', to: 'github_profile#show', as: :github_show_profile
  get '/integrations/github/update', to: 'github_profile#update', as: :github_update_profile
  get '/integrations/github/delete', to: 'github_profile#delete', as: :github_delete_profile 

  get '/integrations/topcoder/new', to: 'topcoder_profile#new', as: :topcoder_profile_new
  post '/integrations/topcoder/create', to: 'topcoder_profile#create', as: :topcoder_profile_create
  get '/integrations/topcoder/show/:username', to: 'topcoder_profile#show_tcp_profile', as: :tcp_show_profile
  get '/integrations/topcoder/update', to: 'topcoder_profile#update', as: :topcoder_update_profile
  get '/integrations/topcoder_profile/delete', to: 'topcoder_profile#delete', as: :topcoder_delete_profile

  get '/integrations/linkedin/create', to: 'linkedin_profile#create', as: :linkedin_profile_create
  get '/integrations/linkedin/show/:username', to: 'linkedin_profile#show_profile', as: :linkedin_show_profile
  post '/integrations/linkedin/refine', to: 'linkedin_profile#refine', as: :linkedin_refine
  get '/integrations/linkedin/update', to: 'linkedin_profile#update', as: :linkedin_update_profile
  get '/integrations/linkedin/delete', to: 'linkedin_profile#delete', as: :linkedin_delete_profile 

  get '/mails/new/:username', to: 'mails#new', as: :new_mails
  post '/mails/send/:username', to: 'mails#send_mail', as: :send_mails
  get '/mails/delete/:id', to: 'mails#delete' , as: :delete_mails

end

app/views/layouts/_center_logo.html.erb
<div class="login-header text-center" style="height: 200px;">
	<a href="<%= home_path %>">
  		<%= image_tag ("logo.png"), class: "logo" %>
  	</a>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class = "container">
		<div class="sociallinks">
			<%= social_share_button_tag("Prologg", :popup => true, :url => "http://prologg.me", :img => "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRtuEzyLbOZbZUskhsEULL7TSJw_EKMitKgWhIMOznJmp8ETZn8hg" ) %>
		</div>
		<div>
			<a href="https://drive.google.com/file/d/0B2n81PJ3ea5bU0d6WHdKYWxaYlk/view?usp=sharing" target="_blank" class="footertext">Help</a>
			<a href="mailto:teameureka.sen@gmail.com" target="_top">Contact</a>
			<a href="https://docs.google.com/forms/d/19-zgzR0Zl2h_pTngO-om3bkfVyCLgnU6x5u6XLCrs9M/viewform" target="_blank">Feedback</a>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<!--
===========================================================
BEGIN PAGE
===========================================================
-->
<!-- BEGIN TOP NAV -->
<div class="top-navbar">
	<div class="top-navbar-inner">
		
		<!-- Begin Logo brand -->
		<div class="logo-brand">
			<%= link_to image_tag("logo.png"), home_path %>
		</div><!-- /.logo-brand -->
		<!-- End Logo brand -->
		
		<div class="top-nav-content">
			
			<!-- Begin button sidebar left toggle -->
			<div class="btn-collapse-sidebar-left">
				<i class="fa fa-bars"></i>
			</div><!-- /.btn-collapse-sidebar-left -->
			<!-- End button sidebar left toggle -->
			
			<!-- Begin button nav toggle -->
			<div class="btn-collapse-nav" data-toggle="collapse" data-target="#main-fixed-nav">
				<i class="fa fa-plus icon-plus"></i>
			</div><!-- /.btn-collapse-sidebar-right -->
			<!-- End button nav toggle -->
			
			
			<!-- Begin user session nav -->
			<ul class="nav-user navbar-right">
				<% if user_signed_in? %>
				<li class="dropdown">
				  <a href="blank.html#fakelink" class="dropdown-toggle" data-toggle="dropdown">
							<%= image_tag(current_user.gravatar_url, class: "avatar img-circle") %>
							Hi, <strong><%= current_user.full_name.split(" ").first %></strong>
						  </a>
						  <ul class="dropdown-menu square primary margin-list-rounded with-triangle">
						  		<li><%= link_to "Show Profile", profile_path(current_user.username) %></li>
								<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
								<li><%= link_to "Edit Integrations", edit_integrations_path, id: "edit_integrations" %></li>
								<li><%= link_to "Edit Links", edit_links_path, id: "edit_links" %></li>
								<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
						  </ul>
				</li>
				<% else %>
					<%= link_to "Sign In", new_user_session_path, class: "btn btn-primary", style: "margin-top: 10px;"  %>
					<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary", style: " margin-top: 10px;" %>
				<% end %>
			</ul>
			<!-- End user session nav -->
			
			<!-- Begin Collapse menu nav -->
			<div class="collapse navbar-collapse" id="main-fixed-nav">
				<!-- Begin nav search form -->
				<a href="<%= search_developer_path %>" class="btn btn-primary searchbtnstyle navbar-left" >
					<i class="fa fa-search"></i>
					Search a developer
				</a>
				<!-- End nav search form -->
				<% if user_signed_in? %>
					<ul class="nav navbar-nav navbar-left">
						<!-- Begin nav notification -->
						<li class="dropdown">
							<a href="index.html#fakelink" class="dropdown-toggle" data-toggle="dropdown">
								
								<% notification_count = current_user.mail_notifications.where(:status=> false).length %>
									<% if not notification_count==0%>
										<span class="badge badge-danger icon-count"  id="notifications_count">
										<%= notification_count %></span>
									<%end%>
									<i class="fa fa-bell"></i>
								</a>
								<ul class="dropdown-menu square with-triangle">
									<li>
									<div class="nav-dropdown-heading">
									Notifications
									</div><!-- /.nav-dropdown-heading -->
									<div class="nav-dropdown-content scroll-nav-dropdown">

										<ul>
											<% if current_user.mail_notifications.length==0 %>
												<center><i class="fa fa-bell icon-lg"></i></center>
												<br>
												<center><strong>No Notification.</strong></center> 
											<% else %>
											<% current_user.mail_notifications.order("id DESC").each do |notification|%>
											<li id="msg_<%=notification.id%>"class="<% if notification.status == false %> unread <% end %>">
												<a href="<%= delete_mails_path(notification.id) %>" style="width:60px; float:right;" method= "delete" data-remote=true>
												<button class="btn btn-default " style="float:right; margin-top: 12px; margin-right: 7px; z-index: 150;" ><i class="fa fa-trash-o"></i>
												</button>
												</a>
												<a href="#" style="padding-right: 30px;">
													<%= image_tag(notification.actor.gravatar_url, class: "absolute-left-content img-circle") %>
													<strong><%= notification.actor.full_name %></strong> sent you a mail.
													<span class="small-caps"><%=distance_of_time_in_words_to_now(notification.created_at)%> ago</span>
												</a>
											</li>
											<% end %>
											<% end %>
										</ul>
									</div><!-- /.nav-dropdown-content scroll-nav-dropdown -->
								</li>
							</ul>
						</li>
					</ul>
				<% end %>
			</div><!-- /.navbar-collapse -->
			<!-- End Collapse menu nav -->
		</div><!-- /.top-nav-content -->
	</div><!-- /.top-navbar-inner -->
</div><!-- /.top-navbar -->
<!-- END TOP NAV -->

<script type="text/javascript">
	$(".btn-collapse-sidebar-left").click(function(){
		"use strict";
		$(".top-navbar").toggleClass("toggle");
		$(".sidebar-left").toggleClass("toggle");
		$(".page-content").toggleClass("toggle");
		$(".icon-dinamic").toggleClass("rotate-180");
		
		if ($(window).width() > 991) {
			if($(".sidebar-right").hasClass("toggle-left") === true){
				$(".sidebar-right").removeClass("toggle-left");
				$(".top-navbar").removeClass("toggle-left");
				$(".page-content").removeClass("toggle-left");
				$(".sidebar-left").removeClass("toggle-left");
				if($(".sidebar-left").hasClass("toggle") === true){
					$(".sidebar-left").removeClass("toggle");
				}
				if($(".page-content").hasClass("toggle") == true){
					$(".page-content").removeClass("toggle");
				}
			}
		}
	});

	$(function () {
		"use strict";
		$('.scroll-nav-dropdown').slimScroll({
			height: '350px',
			position: 'right',
			size: '4px',
			railOpacity: 0.3
		});
	});
</script>

app/views/layouts/_notifications.html.erb
<% unless notice.nil? %>
  <div class="alert alert-warning alert-bold-border fade in alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong>Note!</strong> <%= notice %>
  </div>
<% end %>
<% unless alert.nil? %>
  <div class="alert alert-danger alert-bold-border fade in alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <strong>Alert!</strong> <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prologg</title>
  <link rel="icon" type="image/png" href="/assets/logo-title.png" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style type="text/css"><%= yield :stylesheets %></style>
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	<link href="/assets/style-responsive.css" rel="stylesheet">
	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
	<body class="tooltips">
		<div class="wrapper">
			<div id="header-id">
				<%= render 'layouts/header' %>
			</div>

			<div class="page-content">
					<div class="container-fluid">
						<%= render 'layouts/notifications' %>
						<%= yield %>
					</div>
			</div>
			<div id="footer-id">
				<%= render 'layouts/footer' %>
			</div>
		</div>

		<!-- BEGIN BACK TO TOP BUTTON -->
		<div id="back-top">
			<a href="index.html#top"><i class="fa fa-chevron-up"></i></a>
		</div>
		<!-- END BACK TO TOP -->
		<script type="text/javascript">
			/** BEGIN BACK TO TOP **/
			$(function () {
				$("#back-top").hide();
			});
			$(function () {
				$(window).scroll(function () {
					if ($(this).scrollTop() > 100) {
						$('#back-top').fadeIn();
					} else {
						$('#back-top').fadeOut();
					}
				});
				
				$('#back-top a').click(function () {
					$('body,html').animate({
						scrollTop: 0
					}, 800);
					return false;
				});
			});
			/** END BACK TO TOP **/
			  $("[data-toggle=tooltip]").tooltip();
		</script>

		<script type="text/javascript">
			function ajaxLoad(url) {
				NProgress.start();
				NProgress.inc();
				$.get(url, function() {
					NProgress.done();
				});
			};
		</script>
	</body>
</html>